function DefineVariable(m)
  # Define decision variables (CaseStudy+Obj) 
  JuMP.@variable(m, H[j = 1:numPlant])
  JuMP.@variable(m, ELEV[j = 1:numPlant])
  JuMP.@variable(m, FBVAR[j = 1:numPlant] >= 0)
  JuMP.@variable(m, QTVAR[j = 1:numPlant])
  JuMP.@variable(m, V_SV[j = 1:numPlant] >= 0)
  JuMP.@variable(m, V_AVE[j = 1:numPlant] >= 0)
  JuMP.@variable(m, V_NOW[j = 1:numPlant] >= 0)

  JuMP.@variable(m, V_LIVE[j = 1:numPlant])
  JuMP.@variable(m, QT_NOW[j = 1:numPlant])
  JuMP.@variable(m, QS_NOW[j = 1:numPlant])
  JuMP.@variable(m, QP_NOW[j = 1:numPlant])
  JuMP.@variable(m, P_NOW[j = 1:numPlant, i = 1:numTimeBlock]>=0)

  # Define decision variables (McaArd)
  JuMP.@variable(m, V_TY_Total_now_NOW)
  JuMP.@variable(m, V_TY_Total_SV)
  JuMP.@variable(m, V_IMBALANCE_NOW)
  JuMP.@variable(m, Q_IMBALANCE)
  JuMP.@variable(m, V_IMBALANCE_SV)
  JuMP.@variable(m, V_FLEX_MCA_NOW)
  JuMP.@variable(m, V_FLEX_MCA_SV)
  JuMP.@variable(m, Q_FLEX_MCA)
  JuMP.@variable(m, V_FLEX_ARD_NOW)
  JuMP.@variable(m, V_FLEX_ARD_SV)
  JuMP.@variable(m, Q_FLEX_ARD)
  JuMP.@variable(m, Q_SOA)
  JuMP.@variable(m, V_SOA_SOM)
  JuMP.@variable(m, Q_LCA)
  JuMP.@variable(m, V_LCA_NOW)
  JuMP.@variable(m, V_LCA_SOM)
  JuMP.@variable(m, V_TY_MCA_NOW)
  JuMP.@variable(m, Q_TY_MCA_NOW)
  JuMP.@variable(m, V_TY_MCA_SV)
  JuMP.@variable(m, V_TY_ARD_NOW)
  JuMP.@variable(m, Q_TY_ARD_NOW)
  JuMP.@variable(m, V_TY_ARD_SV)
  JuMP.@variable(m, V_NT_BC_NOW)
  JuMP.@variable(m, V_NT_US_NOW)
  JuMP.@variable(m, V_NT_BC_SV)
  JuMP.@variable(m, V_NT_US_SV)
  JuMP.@variable(m, Q_NT_BC_NOW)
  JuMP.@variable(m, Q_NT_US_NOW)
  JuMP.@variable(m, SPOT_EXP_USH_NOW[i = 1:numTimeBlock]>=0)
  JuMP.@variable(m, SPOT_IMP_USH_NOW[i = 1:numTimeBlock]>=0)
  JuMP.@variable(m, WATER_VALUE >= 0)
  JuMP.@variable(m, LAMBDA >= 0)
  JuMP.@variable(m, INFLOW_NT_BC >= 0)
  JuMP.@variable(m, INFLOW_NT_US >= 0)
  JuMP.@variable(m, INFLOW_TY_MCA >= 0)
  JuMP.@variable(m, INFLOW_TY_ARD >= 0)
  JuMP.@variable(m, INFLOW_FLEX_MCA >= 0)
  JuMP.@variable(m, INFLOW_FLEX_ARD >= 0)
  JuMP.@variable(m, s1 >= 0)
  JuMP.@variable(m, s2 >= 0)
  JuMP.@variable(m, s3 >= 0)
  JuMP.@variable(m, s4 >= 0)
  JuMP.@variable(m, Q_MCA_TY_FLEX)
  JuMP.@variable(m, Q_ARD_TY_FLEX)
  JuMP.@variable(m, Q_MCA_TY_NTBC)
  JuMP.@variable(m, Q_MCA_TY_NTUS)
  JuMP.@variable(m, Q_MCA_NTBC_NTUS)
  JuMP.@variable(m, Q_ARD_TY_LCA)
  JuMP.@variable(m, Q_ARD_TY_IM)
  JuMP.@variable(m, Q_ARD_LCA_IM)
  JuMP.@variable(m, DEFICITIMP[i = 1:numTimeBlock] >=0)
  JuMP.@variable(m, SURPLUSEXP[i = 1:numTimeBlock] >=0)

  return m
end
