startWeatherS = Year(1972)
startDate = Dates.DateTime(2021, 12, 1)
endDate = startDate + Month(numStage - 1)
# Reservoir Inflow
WSR_inflow = TimeSeriesModule.ForecastType(
  Matrix(Output.Q_reservoir_NOW_GMS),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "WSR",
  aCategory = "Reservoir",
  aDataType = "Inflow",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(WSR_inflow, "Output")
DNR_total_inflow = TimeSeriesModule.ForecastType(
  Matrix(Output.Q_reservoir_NOW_PCN),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "DNR",
  aCategory = "Reservoir",
  aDataType = "Inflow",
  aDataTypeQualifier = "Total",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(DNR_total_inflow, "Output")
STC_total_inflow = TimeSeriesModule.ForecastType(
  Matrix(Output.Q_reservoir_NOW_STC),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "STC",
  aCategory = "Reservoir",
  aDataType = "Inflow",
  aDataTypeQualifier = "Total",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(STC_total_inflow, "Output")
KBT_inflow = TimeSeriesModule.ForecastType(
  Matrix(Output.Q_reservoir_NOW_MCA),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "KBT",
  aCategory = "Reservoir",
  aDataType = "Inflow",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(KBT_inflow, "Output")
REV_total_inflow = TimeSeriesModule.ForecastType(
  Matrix(Output.Q_reservoir_NOW_REV),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "REV",
  aCategory = "Reservoir",
  aDataType = "Inflow",
  aDataTypeQualifier = "Total",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(REV_total_inflow, "Output")
ARW_total_inflow = TimeSeriesModule.ForecastType(
  Matrix(Output.Q_reservoir_NOW_ARD),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "ARW",
  aCategory = "Reservoir",
  aDataType = "Inflow",
  aDataTypeQualifier = "Total",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(ARW_total_inflow, "Output")

# Reservoir Storage
WSR_storage = TimeSeriesModule.ForecastType(
  Matrix(Output.V_NOW_value_GMS*3600*24/1000000),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "WSR",
  aCategory = "Reservoir",
  aDataType = "Storage",
  aObservationType = "Instantaneous",
  anInterval = "None",
  aUnits = "Mm3",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(WSR_storage, "Output")
KBT_storage = TimeSeriesModule.ForecastType(
  Matrix(Output.V_NOW_value_MCA*3600*24/1000000),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "KBT",
  aCategory = "Reservoir",
  aDataType = "Storage",
  aObservationType = "Instantaneous",
  anInterval = "None",
  aUnits = "Mm3",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(KBT_storage, "Output")
ARW_storage = TimeSeriesModule.ForecastType(
  Matrix(Output.V_NOW_value_ARD*3600*24/1000000),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "ARW",
  aCategory = "Reservoir",
  aDataType = "Storage",
  aObservationType = "Instantaneous",
  anInterval = "None",
  aUnits = "Mm3",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(ARW_storage, "Output")

# Reservoir Elevation
WSR_elevation = TimeSeriesModule.ForecastType(
  Matrix(Output.H_value_GMS),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "WSR",
  aCategory = "Reservoir",
  aDataType = "Elevation",
  aObservationType = "Instantaneous",
  anInterval = "None",
  aUnits = "m",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
  aDescription = "Williston Monthly Start of Period Reservoir Elevation",
)
TimeSeriesModule.writeXmlFile(WSR_elevation, "Output")
KBT_elevation = TimeSeriesModule.ForecastType(
  Matrix(Output.H_value_MCA),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "KBT",
  aCategory = "Reservoir",
  aDataType = "Elevation",
  aObservationType = "Instantaneous",
  anInterval = "None",
  aUnits = "m",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
  aDescription = "Kinbasket Monthly Start of Period Reservoir Elevation",
)
TimeSeriesModule.writeXmlFile(KBT_elevation, "Output")

# Reservoir Total Discharge
WSR_total_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QP_NOW_val_GMS),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "WSR",
  aCategory = "Reservoir",
  aDataType = "Discharge",
  aDataTypeQualifier = "Total",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
  aDescription = "Kinbasket Monthly Start of Period Reservoir Elevation",
)
TimeSeriesModule.writeXmlFile(WSR_total_discharge, "Output")
DNR_total_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QP_NOW_val_PCN),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "DNR",
  aCategory = "Reservoir",
  aDataType = "Discharge",
  aDataTypeQualifier = "Total",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(DNR_total_discharge, "Output")
STC_total_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QP_NOW_val_STC),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "STC",
  aCategory = "Reservoir",
  aDataType = "Discharge",
  aDataTypeQualifier = "Total",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(STC_total_discharge, "Output")
KBT_total_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QP_NOW_val_MCA),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "KBT",
  aCategory = "Reservoir",
  aDataType = "Discharge",
  aDataTypeQualifier = "Total",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(KBT_total_discharge, "Output")
REV_total_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QP_NOW_val_REV),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "REV",
  aCategory = "Reservoir",
  aDataType = "Discharge",
  aDataTypeQualifier = "Total",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(REV_total_discharge, "Output")
ARW_total_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QP_NOW_val_ARD),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "ARW",
  aCategory = "Reservoir",
  aDataType = "Discharge",
  aDataTypeQualifier = "Total",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(ARW_total_discharge, "Output")


# Reservoir Spill Discharge
WSR_spill_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QS_NOW_val_GMS),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "WSR",
  aCategory = "Reservoir",
  aDataType = "Discharge",
  aDataTypeQualifier = "Spill",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(WSR_spill_discharge, "Output")
PCN_spill_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QS_NOW_val_PCN),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "DNR",
  aCategory = "Reservoir",
  aDataType = "Discharge",
  aDataTypeQualifier = "Spill",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(PCN_spill_discharge, "Output")
STC_spill_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QS_NOW_val_STC),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "STC",
  aCategory = "Reservoir",
  aDataType = "Discharge",
  aDataTypeQualifier = "Spill",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(STC_spill_discharge, "Output")
KBT_spill_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QS_NOW_val_MCA),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "KBT",
  aCategory = "Reservoir",
  aDataType = "Discharge",
  aDataTypeQualifier = "Spill",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(KBT_spill_discharge, "Output")
REV_spill_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QS_NOW_val_REV),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "REV",
  aCategory = "Reservoir",
  aDataType = "Discharge",
  aDataTypeQualifier = "Spill",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(REV_spill_discharge, "Output")
ARW_spill_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QS_NOW_val_ARD),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "ARW",
  aCategory = "Reservoir",
  aDataType = "Discharge",
  aDataTypeQualifier = "Spill",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(ARW_spill_discharge, "Output")

# Hydrp Power Discharge
GMS_power_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QT_NOW_val_GMS),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "GMS",
  aCategory = "Hydro",
  aDataType = "Discharge",
  aDataTypeQualifier = "Power",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(GMS_power_discharge, "Output")
PCN_power_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QT_NOW_val_PCN),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "PCN",
  aCategory = "Hydro",
  aDataType = "Discharge",
  aDataTypeQualifier = "Power",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(PCN_power_discharge, "Output")
STC_power_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QT_NOW_val_STC),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "STC",
  aCategory = "Hydro",
  aDataType = "Discharge",
  aDataTypeQualifier = "Power",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(STC_power_discharge, "Output")
KBT_power_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QT_NOW_val_MCA),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "MCA",
  aCategory = "Hydro",
  aDataType = "Discharge",
  aDataTypeQualifier = "Power",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(KBT_power_discharge, "Output")
REV_power_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QT_NOW_val_REV),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "REV",
  aCategory = "Hydro",
  aDataType = "Discharge",
  aDataTypeQualifier = "Power",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(REV_power_discharge, "Output")
ARW_power_discharge = TimeSeriesModule.ForecastType(
  Matrix(Output.QT_NOW_val_ARD),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "ALH",
  aCategory = "Hydro",
  aDataType = "Discharge",
  aDataTypeQualifier = "Power",
  aObservationType = "Average",
  anInterval = "Forward",
  aUnits = "cms",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(ARW_power_discharge, "Output")

# Hydro Energy
GMS_hydro_energy = TimeSeriesModule.ForecastType(
  Matrix(Output.P_NOW_val_GMS),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "GMS",
  aCategory = "Hydro",
  aDataType = "Energy",
  aObservationType = "Total",
  anInterval = "Forward",
  aUnits = "GWh",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(GMS_hydro_energy, "Output")
PCN_hydro_energy = TimeSeriesModule.ForecastType(
  Matrix(Output.P_NOW_val_PCN),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "PCN",
  aCategory = "Hydro",
  aDataType = "Energy",
  aObservationType = "Total",
  anInterval = "Forward",
  aUnits = "GWh",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(PCN_hydro_energy, "Output")
STC_hydro_energy = TimeSeriesModule.ForecastType(
  Matrix(Output.P_NOW_val_STC),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "STC",
  aCategory = "Hydro",
  aDataType = "Energy",
  aObservationType = "Total",
  anInterval = "Forward",
  aUnits = "GWh",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(STC_hydro_energy, "Output")
KBT_hydro_energy = TimeSeriesModule.ForecastType(
  Matrix(Output.P_NOW_val_MCA),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "MCA",
  aCategory = "Hydro",
  aDataType = "Energy",
  aObservationType = "Total",
  anInterval = "Forward",
  aUnits = "GWh",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(KBT_hydro_energy, "Output")
REV_hydro_energy = TimeSeriesModule.ForecastType(
  Matrix(Output.P_NOW_val_REV),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "REV",
  aCategory = "Hydro",
  aDataType = "Energy",
  aObservationType = "Total",
  anInterval = "Forward",
  aUnits = "GWh",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(REV_hydro_energy, "Output")
ALH_hydro_energy = TimeSeriesModule.ForecastType(
  Matrix(Output.P_NOW_val_ARD),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "ALH",
  aCategory = "Hydro",
  aDataType = "Energy",
  aObservationType = "Total",
  anInterval = "Forward",
  aUnits = "GWh",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(ALH_hydro_energy, "Output")

# Treaty/NonTreaty Account
KBT_treaty_storage = TimeSeriesModule.ForecastType(
  Matrix(Output.V_TY_MCA_NOW_value*3600*24/1000000),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "KBT",
  aCategory = "Account",
  aDataType = "Storage",
  aObservationType = "Instantaneous",
  anInterval = "None",
  aSubCategory = "TSR",
  aUnits = "Mm3",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(KBT_treaty_storage, "Output")
ARW_treaty_storage = TimeSeriesModule.ForecastType(
  Matrix(Output.V_TY_ARD_NOW_value*3600*24/1000000),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "ARW",
  aCategory = "Account",
  aDataType = "Storage",
  aObservationType = "Instantaneous",
  anInterval = "None",
  aSubCategory = "TSR",
  aUnits = "Mm3",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(ARW_treaty_storage, "Output")
KBT_CA_nonTreaty_storage = TimeSeriesModule.ForecastType(
  Matrix(Output.V_NT_BC_NOW_value*3600*24/1000000),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "KBT",
  aCategory = "Account",
  aDataType = "Storage",
  aObservationType = "Instantaneous",
  anInterval = "None",
  aPortfolio = "Canadian",
  aSubCategory = "NonTreaty",
  aUnits = "Mm3",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(KBT_CA_nonTreaty_storage, "Output")
KBT_US_nonTreaty_storage = TimeSeriesModule.ForecastType(
  Matrix(Output.V_NT_US_NOW_value*3600*24/1000000),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "KBT",
  aCategory = "Account",
  aDataType = "Storage",
  aObservationType = "Instantaneous",
  anInterval = "None",
  aPortfolio = "American",
  aSubCategory = "NonTreaty",
  aUnits = "Mm3",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(KBT_US_nonTreaty_storage, "Output")

SYS_Market_Net_Purchase_Energy = TimeSeriesModule.ForecastType(
  Matrix(-Output.Spot_Exp_USH_NOW_value),
  startDate,
  endDate,
  TimestepEnum.Monthly,
  anIdentifierCode = "SYS",
  aCategory = "Market",
  aDataType = "Energy",
  aObservationType = "Total",
  anInterval = "Forward",
  aUnits = "GWh",
  aTransactionType ="Purchase",
  aDataTypeQualifier = "Net",
  aSource = "WVM",
  aNumEnsembleYears = numSimulation,
  startWeatherSequence = startWeatherS,
  aNumDecimalPlaces = 2,
)
TimeSeriesModule.writeXmlFile(SYS_Market_Net_Purchase_Energy, "Output")
